version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
  build_file:
    type: string
    default: "build_vars_dev.tfvars"

orbs:
  aws-s3: circleci/aws-s3@3.0
  aws-cli: circleci/aws-cli@5.4.1

jobs:
  lint-terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.2.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: terraform fmt -check -recursive -diff

  terraform-plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.2.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: terraform plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -var-file=<< parameters.build_file >> -out tfapply
      - store_artifacts:
          path: terraform/tfapply
      - persist_to_workspace:
          root: .
          paths:
            - terraform/tfapply
            - terraform/.*
            - .


  terraform-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.2.1
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve tfapply


workflows:
  version: 2
  plan-approve-and-deploy-to-main:
    unless: << pipeline.parameters.GHA_Action >>
    jobs:
      - lint-terraform:
          filters:
            branches:
              only: main
      - terraform-plan:
          build_file: "build_vars_prod.tfvars"
          requires:
            - lint-terraform
      - plan-approval:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - plan-approval
  plan-and-deploy-to-dev:
    unless: << pipeline.parameters.GHA_Action >>
    jobs:
      - lint-terraform:
          filters:
            branches:
              ignore: main
      - terraform-plan:
          build_file: "build_vars_dev.tfvars"
          requires:
            - lint-terraform
